apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon-clone
  template:
    metadata:
      labels:
        app: amazon-clone
    spec:
      containers:
      - name: amazon-clone
        image: amazon-clone:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-clone-service
spec:
  selector:
    app: amazon-clone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
