name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t amazon-clone .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name amazon-clone-container amazon-clone

    - name: Wait for app to start
      run: sleep 10

    - name: Test app
      run: curl -f http://localhost:3000 || exit 1

    - name: Stop container
      run: docker stop amazon-clone-container
